version: '3.5'

networks:
  default:
    external: true
    name: ${BEAM_NETWORK}

services:
  beam2eth_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/ETH/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=beam2eth_relay.js
      - BEAM_PIPE_CID=$BEAM_PIPE_CID
      - ETH_PIPE_CONTRACT_ADDRESS=$ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$ETH_SIDE_DECIMALS
      - ETH_PIPE_CONTRACT_ABI=EthPipe.json
      - COINGECKO_CURRENCY_RATE_ID=$ETH_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL

  eth2beam_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/ETH/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=eth2beam_relay.js
      - BEAM_PIPE_CID=$BEAM_PIPE_CID
      - ETH_PIPE_CONTRACT_ADDRESS=$ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$ETH_SIDE_DECIMALS
      - ETH_PIPE_CONTRACT_ABI=EthPipe.json
      - COINGECKO_CURRENCY_RATE_ID=$ETH_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL

  beam2usdt_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/USDT/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=beam2eth_relay.js
      - BEAM_PIPE_CID=$USDT_BEAM_PIPE_CID
      - ETH_PIPE_CONTRACT_ADDRESS=$USDT_ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$USDT_ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$USDT_ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$USDT_ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$USDT_ETH_SIDE_DECIMALS
      - COINGECKO_CURRENCY_RATE_ID=$USDT_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL

  usdt2beam_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/USDT/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=eth2beam_relay.js
      - BEAM_PIPE_CID=$USDT_BEAM_PIPE_CID
      - ETH_PIPE_CONTRACT_ADDRESS=$USDT_ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$USDT_ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$USDT_ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$USDT_ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$USDT_ETH_SIDE_DECIMALS
      - COINGECKO_CURRENCY_RATE_ID=$USDT_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL

  beam2dai_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/DAI/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=beam2eth_relay.js
      - BEAM_PIPE_CID=$DAI_BEAM_PIPE_CID
      - ETH_PIPE_CONTRACT_ADDRESS=$DAI_ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$DAI_ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$DAI_ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$DAI_ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$DAI_ETH_SIDE_DECIMALS
      - COINGECKO_CURRENCY_RATE_ID=$DAI_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL

  dai2beam_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/DAI/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=eth2beam_relay.js
      - BEAM_PIPE_CID=$DAI_BEAM_PIPE_CID
      - ETH_PIPE_CONTRACT_ADDRESS=$DAI_ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$DAI_ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$DAI_ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$DAI_ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$DAI_ETH_SIDE_DECIMALS
      - COINGECKO_CURRENCY_RATE_ID=$DAI_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL

  beam2wbtc_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/WBTC/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=beam2eth_relay.js
      - BEAM_PIPE_CID=$WBTC_BEAM_PIPE_CID
      - ETH_PIPE_CONTRACT_ADDRESS=$WBTC_ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$WBTC_ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$WBTC_ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$WBTC_ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$WBTC_ETH_SIDE_DECIMALS
      - COINGECKO_CURRENCY_RATE_ID=$WBTC_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL

  wbtc2beam_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/WBTC/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=eth2beam_relay.js
      - BEAM_PIPE_CID=$WBTC_BEAM_PIPE_CID
      - ETH_PIPE_CONTRACT_ADDRESS=$WBTC_ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$WBTC_ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$WBTC_ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$WBTC_ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$WBTC_ETH_SIDE_DECIMALS
      - COINGECKO_CURRENCY_RATE_ID=$WBTC_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL