version: '3.5'

networks:
  default:
    external: ${USE_EXTERNAL_NETWORK}
    name: ${NETWORK_NAME}

services:
  node:
    profiles: ["api"]
    build:
      context: ./node/
    restart: always
    volumes:
      - ${DATA_PATH}/node/:/home/beam/data/
    ports:
      - ${BEAM_NODE_PORT}:${BEAM_NODE_PORT}
    environment:
      - BEAM_NODE_BINARY=${BEAM_NODE_BINARY}
      - BEAM_WALLET_BINARY=${BEAM_WALLET_BINARY}
      - BEAM_NODE_PEER=${BEAM_NODE_PEER}
      - BEAM_NODE_PORT=${BEAM_NODE_PORT}
      - BEAM_CUSTOM_NETWORK_ARGS=$BEAM_CUSTOM_NETWORK_ARGS
      - WALLET_PASS=$BEAM_WALLET_API_PASS
      - SEED_PHRASE=${BEAM_WALLET_API_SEED_PHRASE}


  api:
    profiles: ["api"]
    build:
      context: ./wallet-api/
    restart: always
    volumes:
      - ${DATA_PATH}/api/:/home/beam/data/
    ports:
      - ${BEAM_WALLET_API_PORT}:${BEAM_WALLET_API_PORT}
    environment:
      - BEAM_WALLET_API_BINARY=${BEAM_WALLET_API_BINARY}
      - BEAM_WALLET_BINARY=${BEAM_WALLET_BINARY}
      - BEAM_NODE_ADR=node:${BEAM_NODE_PORT}
      - SEED_PHRASE=${BEAM_WALLET_API_SEED_PHRASE}
      - WALLET_PASS=$BEAM_WALLET_API_PASS
      - BEAM_CUSTOM_NETWORK_ARGS=$BEAM_CUSTOM_NETWORK_ARGS
      - BEAM_WALLET_API_PORT=$BEAM_WALLET_API_PORT

  beam2eth_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/ETH/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=beam2eth_relay.js
      - BEAM_PIPE_CID=$BEAM_PIPE_CID
      - BEAM_WALLET_API_PORT=$BEAM_WALLET_API_PORT
      - BEAM_BLOCK_CREATION_PERIOD=$BEAM_BLOCK_CREATION_PERIOD
      - BEAM_MIN_CONFIRMATIONS=$BEAM_MIN_CONFIRMATIONS
      - ETH_PIPE_CONTRACT_ADDRESS=$ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$ETH_SIDE_DECIMALS
      - ETH_PIPE_CONTRACT_ABI=$ETH_PIPE_CONTRACT_ABI
      - ETH_HTTP_PROVIDER=$ETH_HTTP_PROVIDER
      - ETH_WEBSOCKET_PROVIDER=$ETH_WEBSOCKET_PROVIDER
      - COINGECKO_CURRENCY_RATE_ID=$ETH_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL
      - RESERVE_CURRENCY_RATE_API_URL=$RESERVE_CURRENCY_RATE_API_URL
      - LOW_FEE_MESSAGES_REFRESH_INTERVAL=$ETH_LOW_FEE_MESSAGES_REFRESH_INTERVAL

  eth2beam_relay:
    build:
      context: ./
    volumes:
      - ${DATA_PATH}/ethrelay/ETH/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=eth2beam_relay.js
      - BEAM_PIPE_CID=$BEAM_PIPE_CID
      - BEAM_WALLET_API_PORT=$BEAM_WALLET_API_PORT
      - ETH_MIN_CONFRIMATIONS=$ETH_MIN_CONFRIMATIONS
      - ETH_PIPE_PUSH_REMOTE_GAS_LIMIT=$ETH_PIPE_PUSH_REMOTE_GAS_LIMIT
      - ETH_PIPE_CONTRACT_ADDRESS=$ETH_PIPE_CONTRACT_ADDRESS
      - ETH_RELAYER_ADDRESS=$ETH_RELAYER_ADDRESS
      - ETH_TOKEN_CONTRACT=$ETH_TOKEN_CONTRACT
      - ETH_RELAYER_PRIVATE_KEY=$ETH_RELAYER_PRIVATE_KEY
      - ETH_SIDE_DECIMALS=$ETH_SIDE_DECIMALS
      - ETH_PIPE_CONTRACT_ABI=$ETH_PIPE_CONTRACT_ABI
      - ETH_HTTP_PROVIDER=$ETH_HTTP_PROVIDER
      - ETH_WEBSOCKET_PROVIDER=$ETH_WEBSOCKET_PROVIDER
      - COINGECKO_CURRENCY_RATE_ID=$ETH_COINGECKO_CURRENCY_RATE_ID
      - GAS_PRICE_API_URL=$GAS_PRICE_API_URL
      - COINGECKO_CURRENCY_RATE_API_URL=$COINGECKO_CURRENCY_RATE_API_URL
      - RESERVE_CURRENCY_RATE_API_URL=$RESERVE_CURRENCY_RATE_API_URL
